- name: Create cluster config file
  template:
    src: valkey-cluster.conf.j2
    dest: "{{ conf_dir }}/valkey.conf"
    mode: '0644'
  notify: Restart Valkey

- name: Start Valkey for cluster
  systemd:
    name: valkey
    enabled: true
    state: started
    command: valkey-server {{ conf_dir }}/valkey.conf

