---
- name: cluster | Create cluster config file
  ansible.builtin.template:
    src: valkey-cluster.conf.j2
    dest: "{{ valkey_config.conf_dir }}/valkey.conf"
    mode: '0644'
  notify: Restart Valkey

- name: cluster | Start Valkey for cluster
  ansible.builtin.systemd:
    name: valkey
    enabled: true
    state: started
    command: valkey-server {{ valkey_config.conf_dir }}/valkey.conf
...