---
- name: Configure | Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ valkey_config.user }}"
    group: "{{ valkey_config.user }}"
    mode: '0755'
  with_items:
    - "{{ valkey_config.conf_dir }}"
    - "{{ valkey_config.data_dir }}"
    - "{{ valkey_config.log_file | dirname }}"
    - "{{ valkey_config.install_dir }}"

- name: configure | Set valkey_cluster group variable
  set_fact:
    cluster_nodes_count: "{{ groups[valkey_cluster] | length }}"
  when: valkey_config.enable_cluster_mode | bool and 'valkey_cluster' in groups

- name: configure | Valkey config present in template
  ansible.builtin.template:
    src: "valkey.conf.j2"
    dest: "{{ valkey_config.conf_dir }}/valkey.conf"
    mode: '0644'
  notify: Restart Valkey

- name: Configure | Set Valkey password in config if requirepass is enabled
  ansible.builtin.lineinfile:
    path: "{{ valkey_config.conf_dir }}/valkey.conf"
    regexp: '^requirepass'
    line: "requirepass {{ valkey_config.requirepass }}"
    state: present
  when: valkey_config.requirepass | length > 0

- name: configure | Copy Valkey systemd service file
  ansible.builtin.template:
    src: valkey.service.j2
    dest: /etc/systemd/system/valkey.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Valkey
  # when: not is_molecule

- name: configure | Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  # when: not is_molecule

- name: configure | Enable and start Valkey
  ansible.builtin.systemd:
    name: valkey
    enabled: true
    state: restarted
  when:
    - ansible_service_mgr == "systemd"
    - "'valkey_cluster' in groups"

- name: configure | Reload systemd to pick up valkey unit file changes
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"
   # - not is_molecule
