- name: Valkey config present in template
  template:
    src: "valkey.conf.j2"
    dest: "{{ conf_dir }}/valkey.conf"
    mode: '0644'
  notify: Restart Valkey

- name: Configure | Create required directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(user) }}"
    group: "{{ item.group | default(user) }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - {path: "{{ conf_dir }}", owner: "{{ user }}", group: "{{ user }}", mode: '0755'}
    - {path: "{{ data_dir }}", owner: "{{ user }}", group: "{{ user }}", mode: '0755'}
    - {path: "{{ log_file | dirname }}", owner: "{{ user }}", group: "{{ user }}", mode: '0755'}
    - {path: "{{ install_dir }}", owner: "{{ user }}", group: "{{ user }}", mode: '0755'}
