---
- name: install | Check if OS-specific variable file exists
  ansible.builtin.stat:
    path: "{{ ansible_os_family }}.yml"
  register: os_var_file

- name: install | Include OS-specific variables if the file exists
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"
  when: os_var_file.stat.exists

- name: install | Ensure dependencies are installed
  ansible.builtin.package:
    name: "{{ valkey_config.item }}"
    state: present
    update_cache: true
  with_items:
    - build-essential
    - tcl
    - wget

- name: install | Download Valkey
  ansible.builtin.get_url:
    url: https://github.com/valkey-io/valkey/archive/refs/tags/{{ version }}.tar.gz
    dest: "/tmp/valkey.tar.gz"

- name: install | Extract Valkey
  ansible.builtin.unarchive:
    src: "/tmp/valkey.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: install | Compile Valkey
  ansible.builtin.make:
    chdir: "/tmp/valkey-{{ valkey_config.version }}"

- name: install | Move binaries
  ansible.builtin.copy:
    src: "/tmp/valkey-{{ valkey_config.version }}/src/valkey-server"
    dest: "{{ valkey_config.install_dir }}/valkey-server"
    remote_src: true
    mode: '0755'

- name: install | Ensure valkey user exists
  ansible.builtin.user:
    name: "{{ valkey_config.user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: install | Install Valkey
  ansible.builtin.apt:
    name: valkey
    state: present
  become: true
...