---
- name: log | Create log directory for Valkey
  ansible.builtin.file:
    path: "{{ valkey_config.log_file | dirname }}"
    state: directory
    owner: "{{ valkey_config.user }}"
    group: "{{ valkey_config.user }}"
    mode: '0755'
...