---
- name: service | Reload systemd to pick up valkey unit file changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: service | Enable and start Valkey
  ansible.builtin.systemd:
    name: valkey
    enabled: true
    state: restarted
...