---
- name: standalone | Copy Valkey systemd service file
  ansible.builtin.template:
    src: valkey.service.j2
    dest: /etc/systemd/system/valkey.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Valkey

- name: standalone | Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: standalone | Enable and start valkey service
  ansible.builtin.systemd:
    name: valkey
    enabled: true
    state: started
...