---
- name: Install Valkey
  ansible.builtin.include_tasks: install.yml

- name: Configure Valkey
  ansible.builtin.include_tasks: configure.yml

- name: Configure cluster Mode
  ansible.builtin.include_tasks: cluster.yml
  when: valkey_config.enable_cluster_mode
...
