---
- name: Verify Valkey Standalone
  hosts: all
  tasks:
    - name: Check if Valkey service is running
      ansible.builtin.service_facts:

    - name: Assert Valkey service is active
      ansible.builtin.assert:
        that:
          - "'valkey' in ansible_facts.services"
          - "ansible_facts.services['valkey'].state == 'running'"
        fail_msg: "Valkey service is NOT running."
        success_msg: "Valkey service is running successfully."
...