- name: Ensure dependencies are installed
  package:
    name: ["build-essential", "tcl", "wget"]
    state: present
    update_cache: yes

- name: Download Valkey
  get_url:
    url:  "https://github.com/valkey-io/valkey/archive/refs/tags/{{ valkey_version }}.tar.gz"

    dest: "/tmp/valkey.tar.gz"

- name: Extract Valkey
  unarchive:
    src: "/tmp/valkey.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Compile Valkey
  make:
    chdir: "/tmp/valkey-{{ valkey_version }}"
    
- name: Ensure /opt/valkey directory exists
  file:
    path: /opt/valkey/src
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Move binaries
  copy:
    src: "/tmp/valkey-{{ valkey_version }}/src/valkey-server"
    dest: "{{ valkey_install_dir }}/valkey-server"
    remote_src: yes
    mode: '0755'

- name: Ensure valkey user exists
  ansible.builtin.user:
    name: "{{ valkey_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

