all:
  children:
    valkey_standalone:
      hosts:
        standalone1:
          ansible_host: "standalone-ip"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

    valkey_cluster:
      hosts:
        cluster1:
          ansible_host: "cluster--node-ip-1"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

        cluster2:
          ansible_host: "cluster--node-ip-2"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

        cluster3:
          ansible_host: "cluster--node-ip-3"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem
