all:
  children:
    valkey_standalone:
      hosts:
        standalone1:
          ansible_host: 98.80.75.221
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

    valkey_cluster:
      hosts:
        cluster1:
          ansible_host: 34.228.21.28
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

        cluster2:
          ansible_host: 54.144.103.83
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

        cluster3:  # typo? should be 'cluster3'?
          ansible_host: 18.208.194.77
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sahil/Downloads/valkey.pem

